### ISSUE TITLE
Autoconfig for markers and encodings

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi-reactive#12]
From dataset we know datapoints availability and concept types of the availability keys.

From component we can know the preferred dimensionality of a marker or encoding.
Excluded names/types for concepts and preferred names/types of concepts

examples:
- line chart wants minimum 2-dimensional space, one of concepts in space should have type: entity domain or set, another should have type: time
- color legend wants 1-dimensional space, where dimension has concept type entity domain or set
- bubblechart wants minimum 1-dim space, where dimension has concept type entity domain or set 
- label encoding prefers a concept of type string, preferred name "name", space should not include concept of type time
- axis encoding prefers a concept of type measure
- another axis encoding prefers a different concept of type measure
- nobody wants to deal with concept of name "tag", even though it's an entity domain
- when there are higher dimensionalities available we should prefer using lower ones (would be weird to start a chart with employment/education/age/gender split all at once)

**Comment by jheeffer** [comment]
This seems to be working fine. If there's specific issues with autoconfig, open a new one describing the failure.
