### ISSUE TITLE
Add encoding.data method .isConstant

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi-reactive#20]
use case
i'd like to hide a color legend on a map when color is a constant
but then i need to calculate the intersection of spaces between encoding and marker in order to check whether color is a constant or not 
this can be added as a convenience method

**Comment by jheeffer** [comment]
https://github.com/vizabi/vizabi-reactive/blob/3403fba60e48231997f6b2ed316e69ea5eeb7114/src/core/dataConfig/dataConfig.js#L60

But I have a feeling that you mean a "constant" as in when there's no overlapping space? Can you please specify what you mean by constant?

**Comment by angieskazka** [comment]
hm, do we have multiple definitions of a constant encoding now?

constant, as set by encoding's own config to be a fixed value, such as `color = "#123456"`
constant, as bound to be a fixed value by space and filter config, because overlap of encoding's space and marker's space is empty, so if marker space is [geo, time] and color space is [gender=male] then the color will always be the same no matter what, but not set by config to be a constant...

so i'd like to cover both situations, maybe even with a single method, for example

encoding.data.doesntChange(){
   return isConstant() || utils.overlap(this.space, this.marker.space).length == 0
} 

then, if color.doesntChange() i hide the legend, which would otherwise show something that isn't informative

**Comment by jheeffer** [comment]
Yeah, the latter is more "constant-like behaviour" because the config leads to a single value being encoded. Similar to when there's only one value in your current data (e.g. filtering euro bubbles and color by world region).

I wonder if a non-overlapping space is even a real-life use case? Why would we ever want that?

**Comment by jheeffer** [comment]
> if marker space is [geo, time] and color space is [gender=male]
> [...]
> then, if color.doesntChange() i hide the legend, which would otherwise show something that isn't informative

I disagree. If you specifically set color to be space: gender, filter: male, then legend should show the color you're using for male. 

It seems you want to hide it whenever you have a range of size 1, so you can just check color.scale.range.length == 1?

Closing for now.
