### ISSUE TITLE
Add user-configurable time limits

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi-reactive#21]
![image](https://user-images.githubusercontent.com/3648190/70871119-05bf3e00-1f9c-11ea-85c8-2bfb70733ca1.png)

**Comment by jheeffer** [comment]
You can configure frame.data.domain?

**Comment by jheeffer** [comment]
`marker.data.filter.dimension = { time: { time: { $gte: 1988 } } }`

I guess this would limit any time query to 1988 and later.

**Comment by jheeffer** [comment]
And now also setting frame.scale.domain. Please reopen if this is still relevant.
