### ISSUE TITLE
confusion with frame value not being formatted

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi-reactive#37]
sometimes frame.value is a date  
Sun Jan 01 2040 01:00:00 GMT+0100 (Central European Standard Time)

sometimes frame value is a string
"2040"

**Comment by jheeffer** [comment]
Please specify how to reproduce. Should correspond to concept_type of frame concept. So reproduction should be of concept_type and value type mismatch.

**Comment by jheeffer** [comment]
Should always be a date, please reopen if it shows up again.
