### ISSUE TITLE
Space is sensitive to the order of dimensions, it shouldn't be

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi-reactive#38]
see attached dataset
[ddf--energy.zip](https://github.com/vizabi/vizabi-reactive/files/5618712/ddf--energy.zip)

ddf--datapoints--energy--by--geo--time--flow.csv
![image](https://user-images.githubusercontent.com/3648190/100664682-47392c80-3358-11eb-84c4-94b3e84177be.png)

attempting to configure tools page line chart
`space: ["flow", "geo", "time"]` works

`space: ["flow",  "time", "geo"]` results in this error

![image](https://user-images.githubusercontent.com/3648190/100664476-f295b180-3357-11eb-942d-8f05f486c706.png)

![image](https://user-images.githubusercontent.com/3648190/100664883-69cb4580-3358-11eb-8012-1c11d0086b4a.png)

![image](https://user-images.githubusercontent.com/3648190/100666013-a26b1f00-3358-11eb-9d87-35fb7e72f773.png)

**Comment by jheeffer** [comment]
Space should be normalized everywhere now (i.e. alphabetically ordered).

Tested and it works now. 

![image](https://user-images.githubusercontent.com/1596071/120065017-86c6a400-c06f-11eb-88d7-c3023552b4b1.png)

![image](https://user-images.githubusercontent.com/1596071/120065135-1ec48d80-c070-11eb-9a7a-89884df27079.png)
