### ISSUE TITLE
Frame model uses data domain instead of domain from config

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi-reactive#39]
![image](https://user-images.githubusercontent.com/3648190/101088600-3b49a680-35b4-11eb-8a3e-5d8d4a63fbfe.png)

on the picture above the last point in time goes to zero, this is because very few datapoints are available for last year 2018, i wonder if i can somehow tell vizabi to not include the last point?
```
          frame: {
            modelType: "frame",
            speed: 200,
            scale: {
              domain: ["1971", "2017"]
            },
            data: {
              concept: {
                autoconfig: {
                  concept_type: "time"
                }
              }
            }
          }
```
i’m trying this, but domain defaults to 1971 - 2018

hmm, it might be using data domain instead of scale domain
![image](https://user-images.githubusercontent.com/3648190/101088654-4c92b300-35b4-11eb-9844-4af969f73169.png)

**Comment by jheeffer** [comment]
Should be capped to scale domain now

![image](https://user-images.githubusercontent.com/1596071/120065341-20428580-c071-11eb-84cf-426a998f7c13.png)

But it seems chart drawing code is not up to par yet:

`viz.model.markers.line.encoding.frame.scale.config.domain = ['1975','2012']`

![image](https://user-images.githubusercontent.com/1596071/120065492-d60dd400-c071-11eb-8ad0-3de3c32b55b6.png)

When dragging:
![image](https://user-images.githubusercontent.com/1596071/120065511-eaea6780-c071-11eb-9301-1d9bc73586ee.png)

![image](https://user-images.githubusercontent.com/1596071/120065533-0ce3ea00-c072-11eb-86ba-0b91848564d6.png)
